lang: ru
title: Резюме Газиев Никита Frontend

name: Газиев Никита
email: zobweyt@gmail.com
website: zobweyt.vercel.app
github: github.com/zobweyt
telegram: t.me/zobweyt

education:
  title: Образование
  items:
    - institution: Центральный университет
      degree: Бакалавриат «Математика и компьютерные науки» (Разработка)
      location: Москва
      date: 2026--2030

achievements:
  title: Достижения
  items:
    - title: Международная олимпиада по промышленной разработке PROD
      role: победитель, лучшая команда
      year: 2025

    - title: Национальная технологическая олимпиада, автоматизация бизнес-процессов
      role: призёр
      year: 2025

    - title: Хакатон Международной олимпиады по промышленной разработке PROD
      role: лучшая команда
      year: 2025

    - title: Хакатон HSE Vibe Hack
      role: лучшая команда
      year: 2025

skills:
  title: Навыки
  items:
    - category: Языки
      list: JavaScript, TypeScript, HTML5, CSS3 (SASS, LESS, TailwindCSS, UnoCSS), Python, SQL, Typst, TeX

    - category: Frontend
      list: React (Next.js, Zustand), SolidJS (Solid Start), Angular (Taiga UI), Astro, Zod, Tanstack Query, Figma

    - category: Backend
      list: Node.js, Bun, Deno, ElysiaJS, FastAPI, Pydantic, Jinja2, Alembic, SQLAlchemy, SQLite, PostgreSQL, Redis

    - category: DevOps
      list: Linux, Docker, Docker Compose, Nginx, Nix, Git, GitHub Actions, GitLab CI/CD, Grafana, Prometheus

    - category: Тестирование
      list: Storybook, Vitest, Playwright, pytest

projects:
  title: Проекты
  items:
    - name: Pay Me More
      date: 2025
      tech: TypeScript, React, Mantine, Tanstack Query, Rsbuild, Biome, Zod, PostCSS, Docker Compose
      link: github.com/zobweyt/pay-me-more
      bullets:
        - В команде разработал UI для ИИ-сервиса для оценки вилки зарплаты и генерации рекомендаций по резюме
        - Добавил drag-and-drop загрузку резюме из PDF, что избавило от необходимости заполнять форму вручную
        - Сделал кэширование сетевых запросов через Tanstack Query и схемную валидацию всех форм через Zod
        - Устранил race conditions путём прерывания неактуальных действующих запросов при переоценке резюме
        - Разработал плавный кастомный лоадер ожидания рекомендаций, улучшив пользовательский опыт (UX)
        - Оптимизировал скорость загрузки данных, распараллелив независимые API-запросы
        - Подключил Grafana и Prometheus для мониторинга производительности системы и метрик удовлетворённости

    - name: Squady
      date: 2025
      tech: TypeScript, React, Recharts, Next.js, SSR, Motion, Maskito, MDX, Docker Compose, shadcn
      link: github.com/rapid-integration/squady
      bullets:
        - Разработал UI платформы формирования команд и управления проектами для хакатонов и олимпиад
        - Сделал дашборд для управления командой и гибкие фильтры поиска мероприятий и резюме участников
        - Добавил плавные взаимодействия и анимации интерфейса для улучшения пользовательского опыта (UX)
        - Подключил MDX для создания кастомной документации, упростив её написание для всей команды разработки
        - Настроил контейнеризацию всей многокомпонентной системы через Docker и Docker Compose

    - name: BookIT
      date: 2025
      tech: TypeScript, SolidJS, Solid Router, TailwindCSS, Vite, Valibot, Modular Forms, Docker Compose
      link: github.com/Central-University-IT-prod/2025-final-command-team-27-bookit
      bullets:
        - В команде разработал интерфейс веб-приложения для бронирования помещений в коворкинге
        - Добавил динамическое отображение занятости мест на интерактивную карту помещений
        - Реализовал бронирование в 2 клика для авторизованных пользователей
        - Создал админ-панель для корректирования информации о пользователях и их прав доступа
        - Подключил интерактивные графики и бизнес-метрики коворкинга через Grafana в админ-панель
        - Разработал клиентский модуль генерации и сканирования QR-кодов для мгновенной верификации бронирований

    - name: Силушка
      date: 2025
      tech: TypeScript, SolidJS, TailwindCSS, IndexedDB, Playwright, Vite, Vitest, Valibot, Modular Forms
      link: github.com/zobweyt/silushka
      bullets:
        - Разработал клиентское фитнес-приложение на архитектуре Feature-Sliced Design (FSD)
        - Настроил локальное хранение данных в IndexedDB и LocalStorage
        - Создал интерфейсы больших форм через Modular Forms с декларативной схемной валидацией через Valibot
        - Добавил геймификацию, анимации, магазин, баланс монет, достижения и динамические реакции аватара
        - Покрыл ключевые пользовательские сценарии E2E-тестами на Playwright и unit-тестами на Vitest
        - Сверстал семантический интерфейс по стандартам доступности WAI-ARIA
    
    - name: textcase
      date: 2025
      tech: Python, MkDocs, PyPI, GitHub Actions, CI/CD, pytest, uv, ruff, ty
      link: github.com/zobweyt/textcase
      bullets:
        - Разработал open-source библиотеку для конвертации регистра текста с ~3.5M скачиваний на PyPI
        - Заменил негибкие аналоги быстрым алгоритмом парсинга без использования регулярных выражений
        - Спроектировал zero-dependency архитектуру с простым кастомным расширением буквально в пару строк
        - Довёл покрытие тестами до 100% и обеспечил полную строгую типизацию всего кода
        - "Настроил CI: отчёты о покрытии тестами и матричное тестирование на версиях Python от 3.9 до самых свежих"
        - "Добавил CD: автоматические релизы на PyPI, деплой на GitHub Pages и предпросмотр документации в PR"
        - Оптимизировал CI/CD-пайплайны через точечный запуск задач только при изменении релевантных файлов
        - Развернул удобную документацию на MkDocs с подключённой аналитикой просмотров и метриками пользы